# Adam Keys' Rails app template
# =============================
#
# Generate an application, just like Adam Keys likes them.

# Testing dependencies
# ------------

gem_group :development, :test do
  gem 'rspec-rails'
end
run "rm -rf test" # Is there a way to set the -T option on the new command?

# Development dependencies
# ------------

gem_group :development do
  gem 'jazz_hands' # Move this to a local Gemfile thingy
  gem 'rack-mini-profiler'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'foreman'
end

# Application dependencies
# ------------------------

# Front-end dependencies
# ----------------------

# Baseline configuration
# ----------------------

# (basic routes, use ENV for configuration values, etc.)

# Vendor front-end bits
# ---------------------

# Grab twitter bootstrap, add it to assets
run %Q{
  url=https://github.com/twbs/bootstrap/archive/v3.0.0.zip
  tmpzip=/tmp/twbs.zip

  curl --location $url > $tmpzip && unzip $tmpzip -d tmp

  mv tmp/bootstrap-3.0.0/dist/js/bootstrap.js vendor/assets/javascripts
  mv tmp/bootstrap-3.0.0/dist/css/bootstrap-*.css vendor/assets/stylesheets
  mv tmp/bootstrap-3.0.0/dist/fonts public/fonts
}
append_file 'app/assets/javascripts/application.js', '//= require bootstrap'
append_file 'app/assets/stylesheets/application.css', ' *= require bootstrap'
append_file 'app/assets/stylesheets/application.css', ' *= require bootstrap-theme'

# Fiddly things
# -------------

run "rm README.rdoc"
run %Q{echo "# An awesome new app!" > README.md}

# Bootstrapping
# -------------

run "bundle install"
generate 'rspec:install'
generate 'jquery:install'

# setup DB
git :init
git add: "."
git commit: %Q{ -m 'Generated by akk_app.rb' }

# Setup Pow
run %Q{
  if [ -d ~/.pow ]; then
    echo 7000 > ~/.pow/`basename $PWD`
    echo "Pow setup!"
  else
    echo "You don't have Pow, so I won't bother with that!"
  fi
}

run %Q{
  if `bin/rake stats >> /dev/null`; then
    echo "Everything's great, write an awesome app!"
  else
    echo "Something went sideways, FIX IT."
  fi
}

# TODO the default app generator runs bundle after this, killing all the lovely
# commentary from the last two commands, fix that!

